disable_existing:
  - body: "*"
    type: mesh

geoms:
  - body: chassis
    attrs:
      name: chassis_collision
      type: box
      pos: "0.044 0 -0.117"
      size: "0.482 0.300 0.134"
      density: "0"
      rgba: "0 0 0 0"
      condim: "4"
      friction: "1.1 0.01 0.001"

  - body: front_left_wheel
    attrs: &wheel_collision
      name: front_left_tire
      type: cylinder
      size: "0.164 0.055"
      density: "0"
      rgba: "0 0 0 0"
      condim: "3"
      friction: "1.4 0.02 0.002"
  - body: front_right_wheel
    attrs:
      <<: *wheel_collision
      name: front_right_tire
  - body: rear_left_wheel
    attrs:
      <<: *wheel_collision
      name: rear_left_tire
  - body: rear_right_wheel
    attrs:
      <<: *wheel_collision
      name: rear_right_tire
