actuators:
  - type: position
    name: front_left_steer_motor
    joint: front_left_steer_joint
    ctrllimited: true
    ctrlrange: [-0.90, 0.90]
    kp: 1200
    kv: 60

  - type: position
    name: front_right_steer_motor
    joint: front_right_steer_joint
    ctrllimited: true
    ctrlrange: [-0.90, 0.90]
    kp: 1200
    kv: 60

  - type: velocity
    name: rear_left_wheel_motor
    joint: rear_left_wheel_joint
    ctrllimited: true
    ctrlrange: [-20, 20]
    kv: 220

  - type: velocity
    name: rear_right_wheel_motor
    joint: rear_right_wheel_joint
    ctrllimited: true
    ctrlrange: [-20, 20]
    kv: 220
