format: hako_pdu_bodies
version: 0.1

robot_name: TB3

base:
  channel_id: 0
  name: base_link_pos
  type: geometry_msgs/Twist
  pdu_size: 72
  body_name: base_link

joints:
  channel_id: 1
  name: joint_states
  type: sensor_msgs/JointState
  pdu_size: auto
  joint_names:
    - wheel_left_joint
    - wheel_right_joint
